version: 2
updates:

  # NuGet
  - package-ecosystem: "nuget" 
    directory: "/src/" 
    schedule:
      interval: "daily"

  # Docker
  - package-ecosystem: "docker" 
    directory: "/" 
    schedule:
      interval: "daily"
